api/urls.py
# Copyright 2016 the Queen's University Biological Station

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


from django.conf.urls import url, include
from api import views


API_TITLE = 'QUBS Data API'
API_DESCRIPTION = 'A web API for accessing data provided by the Queen\'s University Biological Station'


urlpatterns = [
    url(r'^$', views.api_root, name='qubs-api-root'),

    url(r'^climate/', include('climate_data.urls')),
    url(r'^herbarium/', include('herbarium_data.urls')),

    url(r'^users/$', views.UserList.as_view(), name='user-list'),
    url(r'^users/(?P<pk>[0-9]+)/$', views.UserDetail.as_view(), name='user-detail'),

    url(r'^api-auth/', include('rest_framework.urls')),
]

climate_manager/urls.py
from django.conf.urls import url
from climate_manager import views

urlpatterns = [
    url(r'^$', views.index, name='climate-manager-index'),

    url(r'^stations/(?P<pk>[0-9]+)/$', views.station_overview, name='station'),
    url(r'^stations/(?P<pk>[0-9]+)/(?P<data_type>[a-zA-Z0-9_]+)/$', views.station__data_type,
        name='station__data_type'),
    url(r'^stations/(?P<pk>[0-9]+)/(?P<data_type>[a-zA-Z0-9_]+)/chart.png$',
        views.station_chart, name='station__data_type__chart'),

    url(r'^data-types/(?P<data_type>[a-zA-Z0-9_]+)/$', views.data_type_overview,
        name='data_type')
]

qubs_data_centre/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views


admin.site.site_header = 'QUBS Data Centre Admin'

urlpatterns = [
    url(r'^', include('core.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^climate/export/', include('climate_exporter.urls')),
    url(r'^climate/manage/', include('climate_manager.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', auth_views.LoginView.as_view(), name='login'),
]

# If in debug mode, serve static files from Django.
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

climate_manager/forms.py
from django import forms

from climate_data.models import *


class InvalidateDataForm(forms.Form):
    station = forms.ModelChoiceField(queryset=Station.objects.all())
    data_type = forms.ModelChoiceField(queryset=DataType.objects.all())

    time_start = forms.DateTimeField()
    time_end = forms.DateTimeField()


class DataTypeInvalidateDataForm(forms.Form):
    station = forms.ModelChoiceField(queryset=Station.objects.all())

    time_start = forms.DateTimeField()
    time_end = forms.DateTimeField()


class StationDataTypeInvalidateDataForm(forms.Form):
    time_start = forms.DateTimeField()
    time_end = forms.DateTimeField()


class LogUploadForm(forms.Form):
    LOG_FORMAT_CHOICES = (
        ('satlink_std', 'Satlink Standard CSV (SatLink2)'),
        ('sutron_std', 'Sutron Standard CSV (XLite, SatLink3)'),
        ('pendant_event', 'HOBO Pendant Event Logger CSV'),
    )

    format = forms.ChoiceField(choices=LOG_FORMAT_CHOICES)
    log = forms.FileField()

climate_manager/views.py
import json
import datetime
import pytz
import numpy

from matplotlib.figure import Figure
from matplotlib.backends.backend_agg import FigureCanvasAgg
from matplotlib.dates import DateFormatter, date2num

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseBadRequest, Http404
from django.shortcuts import render
from rest_framework.renderers import JSONRenderer

from climate_manager.forms import *

from climate_data.models import *
from climate_data.serializers import *


@login_required
def index(request):
    station_data_types = {
        s.id: [l.data_type.id for l in StationSensorLink.objects.filter(station=s).iterator()]
        for s in Station.objects.all().iterator()
    }

    if request.method == 'POST':
        form = InvalidateDataForm(request.POST)

        if form.is_valid():
            station = form.cleaned_data['station']
            data_type = form.cleaned_data['data_type']

            time_start = form.cleaned_data['time_start']
            time_end = form.cleaned_data['time_end']

            queryset = Reading.objects.filter(
                station=station,
                station_sensor_link__data_type=data_type,

                read_time__gte=time_start,
                read_time__lte=time_end,

                invalid=False  # Don't bother re-invalidating readings - plus, it throws the count off.
            )

            count = queryset.count()

            if count > 0:
                queryset.update(invalid=True, qc_processed=True)

                messages.success(
                    request,
                    'Invalidated {count} readings from {station_name} on interval [{s}, {e}].'.format(
                        count=count,
                        station_name=station.name,

                        s=time_start,
                        e=time_end
                    )
                )
            else:
                messages.info(request, 'No (non-invalid) readings were found within those restrictions.')

        else:
            messages.error(request, 'The command submitted was not valid.')

    else:
        form = InvalidateDataForm()

    return render(request, 'climate_manager/index.html', {
        'invalidation_form': form,

        'stations': list(Station.objects.all().values()),
        'stations_json': JSONRenderer().render([StationSerializer(s).data for s in Station.objects.all().iterator()])
                                       .decode('utf-8'),
        'station_data_types': JSONRenderer().render(station_data_types).decode('utf-8')
    })


@login_required
def station_overview(request, pk=None):
    try:
        pk = int(pk)
    except TypeError:
        return HttpResponseBadRequest()

    try:
        station = Station.objects.get(id=pk)
    except Station.DoesNotExist:
        raise Http404('Station does not exist')

    if request.method == 'POST':
        log_upload_form = LogUploadForm(request.POST)

        # if log_upload_form.is_valid():

    else:
        log_upload_form = LogUploadForm()

    station_data_types = [
        l.data_type for l in StationSensorLink.objects.filter(station=station).select_related('data_type').iterator()
    ]

    return render(request, 'climate_manager/station.html', {
        'station': station,
        'log_upload_form': log_upload_form,
        'station_data_types': [DataTypeSerializer(d).data for d in station_data_types],
    })


@login_required
def station__data_type(request, pk=None, data_type=None):
    try:
        pk = int(pk)
    except TypeError:
        return HttpResponseBadRequest()

    if data_type is None:
        return HttpResponseBadRequest()

    try:
        station = Station.objects.get(id=pk)
    except Station.DoesNotExist:
        raise Http404('Station does not exist')

    try:
        data_type = DataType.objects.get(short_name=data_type)
    except DataType.DoesNotExist:
        raise Http404('Data type does not exist')

    station_sensor_link = StationSensorLink.objects.get(station=station, data_type=data_type)

    if request.method == 'POST':
        form = StationDataTypeInvalidateDataForm(request.POST)

        if form.is_valid():
            time_start = form.cleaned_data['time_start']
            time_end = form.cleaned_data['time_end']

            queryset = Reading.objects.filter(
                station=station,
                station_sensor_link__data_type=data_type,

                read_time__gte=time_start,
                read_time__lte=time_end,

                invalid=False  # Don't bother re-invalidating readings - plus, it throws the count off.
            )

            count = queryset.count()

            if count > 0:
                queryset.update(invalid=True, qc_processed=True)

                messages.success(
                    request,
                    'Invalidated {count} readings on interval [{s}, {e}].'.format(
                        count=count,
                        station_name=station.name,

                        s=time_start,
                        e=time_end
                    )
                )
            else:
                messages.info(request, 'No (non-invalid) readings were found within those restrictions.')

        else:
            messages.error(request, 'The command submitted was not valid.')

    else:
        form = StationDataTypeInvalidateDataForm()

    # Fetch data after potential invalidations.
    graph_data = [[r.read_time, r.decimal_value()] for r in Reading.objects.filter(
        station_sensor_link=station_sensor_link,
        invalid=False
    ).only('read_time', 'value', 'sensor').select_related('sensor').order_by('read_time').iterator()]

    return render(request, 'climate_manager/station__data_type.html', {
        'invalidation_form': form,

        'station': station,
        'data_type': data_type,
        'graph_data': JSONRenderer().render(graph_data).decode('utf-8')
    })


def station_chart(request, pk=None, data_type=None):
    try:
        pk = int(pk)
    except TypeError:
        return HttpResponseBadRequest()

    if data_type is None:
        return HttpResponseBadRequest()

    try:
        station = Station.objects.get(id=pk)
    except Station.DoesNotExist:
        raise Http404('Station does not exist')

    try:
        data_type = DataType.objects.get(short_name=data_type)
    except DataType.DoesNotExist:
        raise Http404('Data type does not exist')

    station_sensor_link = StationSensorLink.objects.get(station=station, data_type=data_type)

    data = list(Reading.objects.filter(
        station_sensor_link=station_sensor_link,
        invalid=False,
        read_time__gte=datetime.datetime.now(pytz.utc)-datetime.timedelta(days=31)
    ).only('read_time', 'value', 'sensor').select_related('sensor').order_by('read_time'))

    chart = Figure()
    ax = chart.add_subplot(111)

    x = [r.read_time for r in data if (r.decimal_value() is None or r.decimal_value() in data_type.bounds)]
    y = [r.decimal_value() for r in data if (r.decimal_value() is None or r.decimal_value() in data_type.bounds)]

    all_nan = True

    for i in range(0, len(y)):
        if y[i] is None:
            y[i] = numpy.nan
        elif all_nan:
            all_nan = False

    if all_nan:
        # Prevent a strange error with date axis conversion from matplotlib.
        x = []
        y = []

    ax.plot_date(x, y, '-')
    ax.xaxis.set_major_formatter(DateFormatter('%Y-%m-%d'))
    chart.autofmt_xdate()

    response = HttpResponse(content_type='image/png')
    FigureCanvasAgg(chart).print_png(response)

    return response


@login_required
def data_type_overview(request, data_type=None):
    if data_type is None:
        return HttpResponseBadRequest()

    try:
        data_type = DataType.objects.get(short_name=data_type)
    except DataType.DoesNotExist:
        raise Http404('Data type does not exist')

    if request.method == 'POST':
        form = DataTypeInvalidateDataForm(request.POST)

        if form.is_valid():
            station = form.cleaned_data['station']

            time_start = form.cleaned_data['time_start']
            time_end = form.cleaned_data['time_end']

            queryset = Reading.objects.filter(
                station=station,
                station_sensor_link__data_type=data_type,

                read_time__gte=time_start,
                read_time__lte=time_end,

                invalid=False  # Don't bother re-invalidating readings - plus, it throws the count off.
            )

            count = queryset.count()

            if count > 0:
                queryset.update(invalid=True, qc_processed=True)

                messages.success(
                    request,
                    'Invalidated {count} readings from {station_name} on interval [{s}, {e}].'.format(
                        count=count,
                        station_name=station.name,

                        s=time_start,
                        e=time_end
                    )
                )
            else:
                messages.info(request, 'No (non-invalid) readings were found within those restrictions.')

        else:
            messages.error(request, 'The command submitted was not valid.')

    else:
        form = DataTypeInvalidateDataForm()

    # Fetch data after potential invalidations.
    graph_data = [{
        'name': s.name,
        'data': [[r.read_time, r.decimal_value()] for r in Reading.objects.filter(
            station_sensor_link__station=s,
            station_sensor_link__data_type=data_type,
            invalid=False
        ).only('read_time', 'value', 'sensor', 'station_sensor_link').select_related('sensor', 'station_sensor_link')
            .order_by('read_time').iterator()]
    } for s in Station.objects.all().iterator()]

    return render(request, 'climate_manager/data_type.html', {
        'invalidation_form': form,

climate_manager/templates/climate_manager/data_type.html
{% extends "generic_base.html" %}
{% load static %}

{% block title %}{{ data_type.name }} | Climate Data Manager{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static "climate_manager/style.css" %}">

    <script src="http://code.highcharts.com/stock/highstock.js"></script>

    <!-- Flatpickr -->
    <link rel="stylesheet" href="https://unpkg.com/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" type="text/css" href="https://npmcdn.com/flatpickr/dist/themes/material_red.css">
    <script src="https://unpkg.com/flatpickr" type="text/javascript"></script>
    <style type="text/css">
        .flatpickr-current-month {
            font-size: 110%;
        }
    </style>

    <!--suppress JSCheckFunctionSignatures -->
    <script type="text/javascript">
        const data = JSON.parse('{{ graph_data|escapejs }}').map(function (s) {
            s['data'] = s['data'].map(function (x) {
                return [Date.parse(x[0]), x[1]];
            });

            return s;
        });

        Highcharts.setOptions({
			global : { useUTC : true }
		});

        Highcharts.theme = {
			colors: ['#F44336', '#9C27B0', '#03A9F4', '#CDDC39', '#FF9800', '#607D8B', '#009688', '#FFEB3B', '#3F51B5'],
			chart: {backgroundColor: '#FEFEFE'},
			title: {
				style: {
					color: '#424242',
					font: '600 1rem "Open Sans", sans-serif'
				}
			},
			subtitle: {
				style: {
					color: '#9E9E9E',
					font: 'normal 0.8rem "Open Sans", sans-serif'
				}
			},

			xAxis: {
				gridLineColor: '#EEEEEE',
				gridLineWidth: 1,

				lineColor: '#E0E0E0',
				tickColor: '#E0E0E0',

				labels: {
					style: { font: 'normal 0.7rem "Open Sans", sans-serif' }
				}
			},

			yAxis: {
				gridLineColor: '#EEEEEE',
				gridLineWidth: 1,
				labels: {
					style: { font: 'normal 0.7rem "Open Sans", sans-serif' }
				}
			},

            legend: {
			    enabled: false
            },

			scrollbar: {
				barBackgroundColor: '#CFD8DC'
			}
		};

		// Apply the theme
		Highcharts.setOptions(Highcharts.theme);

        document.addEventListener('DOMContentLoaded', function () {
            var dateRange = new Date();
            dateRange.setDate(dateRange.getDate() - 31);

            const chartOptions = {
                title: {text: ''},
                subtitle: {text: ''},

                xAxis: {
                    type: 'datetime',
                    tickPixelInterval: 150,
                    min: dateRange.getTime(),
                    max: (new Date()).getTime()
                },

                yAxis: {
                    title: {text: '{{ data_type.name|escapejs }}'},
                    plotLines: [{
                        value: 0,
                        width: 1,
                        color: '#FF5722'
                    }]
                },

                tooltip: {valueSuffix: '{{ data_type.unit|escapejs }}'},
                scrollbar: {enabled: true},

                plotOptions: {
                    series: {
                        marker: {enabled: false},
                        gapSize: 5
                    }
                },

                rangeSelector: {
                    enabled: true,
                    inputPosition: {
                        align: 'right',
                        y: 0
                    }
                },

                navigator: {
                    enabled: true
                },

                chart: {
                    renderTo: 'graph-container',
                    type: 'line',
                    animation: Highcharts.svg,
                    zoomType: 'x',
                    spacingTop: 40
                },

                series: data
            };

            const chart = new Highcharts.Chart(chartOptions);

            const timeStart = flatpickr('#id_time_start', {
                enableTime: true,
                time_24hr: true,
                altInput: true
            });
            const timeEnd = flatpickr('#id_time_end', {
                enableTime: true,
                time_24hr: true,
                altInput: true
            });

            document.getElementById('importBounds').addEventListener('click', function () {
                if (chart.series[0].points.length > 2) {
                    var startDate = new Date(chart.series[0].points[1].x);
                    var endDate = new Date(chart.series[0].points[chart.series[0].points.length - 2].x);

                    timeStart.setDate(startDate.getUTCFullYear().toString() + '-' + (startDate.getUTCMonth() + 1) + '-'
                        + startDate.getUTCDate() + ' ' + startDate.getUTCHours() + ':' + startDate.getUTCMinutes());
                    timeEnd.setDate(endDate.getUTCFullYear().toString() + '-' + (endDate.getUTCMonth() + 1) + '-'
                        + endDate.getUTCDate() + ' ' + endDate.getUTCHours() + ':' + endDate.getUTCMinutes());
                }
            });
        }, false);
    </script>
{% endblock %}

{% block content %}
    <h1>QUBS Climate Data Manager</h1>
    <h2>
        <a href="{% url 'index' %}"><i class="material-icons">home</i></a>
        <i class="material-icons">arrow_forward</i>
        <a href="{% url 'data_type' data_type.short_name %}">{{ data_type.name }}</a>
    </h2>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <p><em>All times are in UTC.</em></p>
    <h3>Chart</h3>
    <div id="graph-container"></div>
    <h3>Data Invalidation</h3>
    <form action="" method="post">
        {% csrf_token %}
        <p>
            Invalidate data from <label for="{{ invalidation_form.station.id_for_label }}">station</label>
            {{ invalidation_form.station }} between dates {{ invalidation_form.time_start }}
            and {{ invalidation_form.time_end }} inclusive. <br>
            <button type="button" id="importBounds">Use Bounds from Chart</button>
        </p>
        <p class="form-help-text">
            Will mark any data invalidated as having also gone through a quality control process.
        </p>
        <button value="submit">Submit</button>
    </form>
{% endblock %}

climate_manager/templates/climate_manager/index.html
{% extends "generic_base.html" %}
{% load static %}

{% block title %}Climate Data Manager{% endblock %}

{% block head %}

<link rel="stylesheet" href="{% static "climate_manager/style.css" %}">

<!-- Flatpickr -->
<link rel="stylesheet" href="https://unpkg.com/flatpickr/dist/flatpickr.min.css">
<link rel="stylesheet" type="text/css" href="https://npmcdn.com/flatpickr/dist/themes/material_red.css">
<script src="https://unpkg.com/flatpickr" type="text/javascript"></script>
<style type="text/css">
    .flatpickr-current-month {
        font-size: 120%;
    }
</style>

<script type="text/javascript">
    const stations = JSON.parse('{{ stations_json|escapejs }}');
    const stationDataTypes = JSON.parse('{{ station_data_types|escapejs }}');

    var selectedStation = null;

    document.addEventListener('DOMContentLoaded', function () {
        const stationSelector = document.getElementById('{{ invalidation_form.station.id_for_label }}');
        const dataTypeSelector= document.getElementById('{{ invalidation_form.data_type.id_for_label }}');

        stationSelector.addEventListener('change', function () {
            selectedStation = parseInt(stationSelector.value, 10);
            if (isNaN(selectedStation)) {
                selectedStation = null;
            }

            for (var d in dataTypeSelector.children) {
                if (dataTypeSelector.children.hasOwnProperty(d)) {
                    var currentDataTypeID = parseInt(dataTypeSelector[d].value, 10);

                    if (isNaN(currentDataTypeID)) {
                        currentDataTypeID = -1;
                    }
                    if (typeof stationDataTypes[selectedStation] !== 'undefined') {
                        if (stationDataTypes[selectedStation].indexOf(currentDataTypeID) === -1) {
                            dataTypeSelector.children[d]['disabled'] = true;
                            if (dataTypeSelector[d].value === dataTypeSelector.children[d]['value']) {
                                dataTypeSelector.children[d]['selected'] = false;
                            }
                        } else {
                            dataTypeSelector.children[d]['disabled'] = false;
                        }
                    } else {
                        // Show everything if nothing is selected.
                        dataTypeSelector.children[d]['disabled'] = false;
                    }
                }
            }
        }, false);

        flatpickr('#id_time_start', {
            enableTime: true,
            altInput: true
        });
        flatpickr('#id_time_end', {
            enableTime: true,
            altInput: true
        });
    }, false);
</script>

{% endblock %}

{% block content %}
    <h1>QUBS Climate Data Manager</h1>

    <h2><i class="material-icons">home</i></h2>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <h3>Stations</h3>

    <ul id="station-list">
        {% for station in stations %}
            <li><a href="{% url 'station' station.id %}">{{ station.name }}</a></li>
        {% endfor %}
    </ul>

    <h3>Data Invalidation</h3>
    <form action="/climate/manage/" method="post">
        {{ invalidation_form.station.errors }}
        {% csrf_token %}
        <p>
            Invalidate data from <label for="{{ invalidation_form.station.id_for_label }}">station</label>
            {{ invalidation_form.station }} with
            <label for="{{ invalidation_form.data_type.id_for_label }}">data type</label>
            {{ invalidation_form.data_type }} between dates {{ invalidation_form.time_start }} and
            {{ invalidation_form.time_end }} inclusive.
        </p>
        <p class="form-help-text">
            Will mark any data invalidated as having also gone through a quality control process.
        </p>
        <button value="submit">Submit</button>
    </form>
{% endblock %}

climate_manager/templates/climate_manager/station__data_type.html
{% extends "generic_base.html" %}
{% load static %}

{% block title %}{{ data_type.name }} | {{ station.name }} | Climate Data Manager{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static "climate_manager/style.css" %}">

    <script src="http://code.highcharts.com/stock/highstock.js"></script>

    <!-- Flatpickr -->
    <link rel="stylesheet" href="https://unpkg.com/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" type="text/css" href="https://npmcdn.com/flatpickr/dist/themes/material_red.css">
    <script src="https://unpkg.com/flatpickr" type="text/javascript"></script>
    <style type="text/css">
        .flatpickr-current-month {
            font-size: 110%;
        }
    </style>

    <!--suppress JSCheckFunctionSignatures -->
    <script type="text/javascript">
        const data = {
            name: '{{ data_type.name|escapejs }}',
            data: JSON.parse('{{ graph_data|escapejs }}').map(function (x) {
                return [Date.parse(x[0]), x[1]]
            })
        };

        Highcharts.setOptions({
			global : { useUTC : true }
		});

        Highcharts.theme = {
			colors: ['#03A9F4'],
			chart: {backgroundColor: '#FEFEFE'},
			title: {
				style: {
					color: '#424242',
					font: '600 1rem "Open Sans", sans-serif'
				}
			},
			subtitle: {
				style: {
					color: '#9E9E9E',
					font: 'normal 0.8rem "Open Sans", sans-serif'
				}
			},

			xAxis: {
				gridLineColor: '#EEEEEE',
				gridLineWidth: 1,

				lineColor: '#E0E0E0',
				tickColor: '#E0E0E0',

				labels: {
					style: { font: 'normal 0.7rem "Open Sans", sans-serif' }
				}
			},

			yAxis: {
				gridLineColor: '#EEEEEE',
				gridLineWidth: 1,
				labels: {
					style: { font: 'normal 0.7rem "Open Sans", sans-serif' }
				}
			},

            legend: {
			    enabled: false
            },

			scrollbar: {
				barBackgroundColor: '#CFD8DC'
			}
		};

		// Apply the theme
		Highcharts.setOptions(Highcharts.theme);

        document.addEventListener('DOMContentLoaded', function () {
            var dateRange = new Date();
            dateRange.setDate(dateRange.getDate() - 31);

            const chartOptions = {
                title: {text: ''},
                subtitle: {text: ''},

                xAxis: {
                    type: 'datetime',
                    tickPixelInterval: 150,
                    min: dateRange.getTime(),
                    max: (new Date()).getTime()
                },

                yAxis: {
                    title: {text: '{{ data_type.name|escapejs }}'},
                    plotLines: [{
                        value: 0,
                        width: 1,
                        color: '#FF5722'
                    }]
                },

                tooltip: {valueSuffix: '{{ data_type.unit|escapejs }}'},
                scrollbar: {enabled: true},

                plotOptions: {
                    series: {
                        marker: {enabled: false},
                        gapSize: 5
                    }
                },

                rangeSelector: {
                    enabled: true,
                    inputPosition: {
                        align: 'right',
                        y: 0
                    }
                },

                navigator: {
                    enabled: true
                },

                chart: {
                    renderTo: 'graph-container',
                    type: 'line',
                    animation: Highcharts.svg,
                    zoomType: 'x',
                    spacingTop: 40
                },

                series: [data]
            };

            const chart = new Highcharts.Chart(chartOptions);

            const timeStart = flatpickr('#id_time_start', {
                enableTime: true,
                time_24hr: true,
                altInput: true
            });
            const timeEnd = flatpickr('#id_time_end', {
                enableTime: true,
                time_24hr: true,
                altInput: true
            });

            document.getElementById('importBounds').addEventListener('click', function () {
                if (chart.series[0].points.length > 2) {
                    var startDate = new Date(chart.series[0].points[1].x);
                    var endDate = new Date(chart.series[0].points[chart.series[0].points.length - 2].x);

                    timeStart.setDate(startDate.getUTCFullYear().toString() + '-' + (startDate.getUTCMonth() + 1) + '-'
                        + startDate.getUTCDate() + ' ' + startDate.getUTCHours() + ':' + startDate.getUTCMinutes());
                    timeEnd.setDate(endDate.getUTCFullYear().toString() + '-' + (endDate.getUTCMonth() + 1) + '-'
                        + endDate.getUTCDate() + ' ' + endDate.getUTCHours() + ':' + endDate.getUTCMinutes());
                }
            });
        }, false);
    </script>
{% endblock %}

{% block content %}
    <h1>QUBS Climate Data Manager</h1>
    <h2>
        <a href="{% url 'climate-manager-index' %}"><i class="material-icons">home</i></a>
        <i class="material-icons">arrow_forward</i>
        <a href="{% url 'station' station.id %}">{{ station.name }}</a>
        <i class="material-icons">arrow_forward</i>
        <span>{{ data_type.name }}</span>
    </h2>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <p><em>All times are in UTC.</em></p>
    <h3>Chart</h3>
    <div id="graph-container"></div>
    <h3>Data Invalidation</h3>
    <form action="" method="post">
        {% csrf_token %}
        <p>
            Invalidate data between dates {{ invalidation_form.time_start }}
            and {{ invalidation_form.time_end }} inclusive.
            <button type="button" id="importBounds" style="margin-left: 0.5em;">Use Bounds from Chart</button>
        </p>
        <p class="form-help-text">
            Will mark any data invalidated as having also gone through a quality control process.
        </p>
        <button value="submit">Submit</button>
    </form>
{% endblock %}